---
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-sata
  name: vmi-sata
spec:
  domain:
    devices: {}
    memory:
      guest: 128Mi
    resources: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: icoy/cirros-container-disk-demo:dev
    name: containerdisk
